### ISSUE TITLE
Installation not found with EA App version

### ISSUE THREAD

**Issue by fdev3000** [OpenRA/TiberianDawnHD#25]
Hi,

it seems EA replaced Origin by the EA App and updated CnC Remastered. Even though the registry keys in mod.yaml are still present, TiberianDawnHD can't find the installation. 

I don't know the directory layout of the origin version but looking at the paths in mod.yam I recognize that there is no CNCDATA folder in the installation root. It might have moved to DATA/CNCDATA.

Best regards

**Comment by pchote** [comment]
I transferred the previous issue to https://github.com/OpenRA/OpenRA/issues/20763, as the bug is in the upstream OpenRA logic.
