### ISSUE TITLE
Origin / EA App content installation is failing

### ISSUE THREAD

**Issue by penev92** [OpenRA/TiberianDawnHD#26]
Reports have been coming in over the past few months, which roughly coincided with the launch of the new EA App that replaced Origin, so we blamed that.
Turns out it was https://github.com/OpenRA/OpenRA/commit/7188f88ba1ef66a8379b39784cb6e29772127fc4 that broke content source detection because mod.yaml does not define `IDFiles`:
```miniyaml
RemasterModContent:
	RemasterDataMount: data
	Sources:
		steam:
			Type: Steam
				AppId: 1213210
		origin:
			Type: RegistryDirectory
			RegistryPrefixes: HKEY_LOCAL_MACHINE\Software\, HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\
			RegistryKey: Petroglyph\CnCRemastered
			RegistryValue: Install Dir
```

Since that commit several SourceResolvers, including `RegistryDirectorySourceResolver`, which is what the `origin` source uses, require `IDFiles`.

**Comment by IceReaper** [comment]
Sound like https://github.com/OpenRA/OpenRA/pull/20776 to me ;)

**Comment by IceReaper** [comment]
As my linked PR is merged, this needs an IDFiles entry.
While it will no longer crash when using https://github.com/OpenRA/OpenRA/pull/20791 it will run into another problem mentioned in the other PR: If you delete the game folder, the steam app manifest file, or the ea registry entry will still be present, hence resolving. I highly suggest to add IDFiles to this installer file for this case!

**Comment by pchote** [comment]
Fixed in the new playtest build.
