### ISSUE TITLE
Tint is only applied to some tiles

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/TiberianDawnHD#27]
![grafic](https://github.com/OpenRA/TiberianDawnHD/assets/37534529/a79b4c99-ac90-4aa6-ad1e-4f46a0951318)

**Comment by pchote** [comment]
Will be fixed by https://github.com/OpenRA/OpenRA/pull/21142.

**Comment by pchote** [comment]
Fixed in https://github.com/OpenRA/TiberianDawnHD/releases/tag/release-20231010-v2.
